/*      Copyright 2002 Arizona Board of regents on behalf of 
 *                  The University of Arizona 
 *                     All Rights Reserved 
 *         (USE & RESTRICTION - Please read COPYRIGHT file) 
 * 
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 08-15-02 
 */ 


package SimpMod;

import java.awt.*;
import java.util.*;

import GenCol.*;


import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;



public class multiServer extends ViewableDigraph{



public multiServer() {this("multi", 200, 20);}

public multiServer(String name,double proc_time,int size)
{
 super(name);
 make(proc_time,size);
 addTestInput("in", new entity("job"));
}


 private void make(double proc_time,int size){

    addInport("in");
    addOutport("out");

    multiServerCoord  co  = new multiServerCoord("MultiSco");
   add(co);

 for (int i = 1; i <= size; i++){
     proc  p = new procName("proc" + i, proc_time);
    add(p);
   co.add_procs(p);
    p.setPreferredLocation(new Point(187, 22 + 80 * (i - 1)));

  }

    Iterator i = getComponents().iterator();
    while (i.hasNext()) {
       entity ent = (entity)i.next();
       devs comp = (devs)ent;
   if (!ent.equals(co))
  {
    addCoupling(co, "y", comp,"inName"); //use name for routing
    addCoupling(comp,"outName",co,"x");
  }

  }
    addCoupling(this,"in",co,"in");
    addCoupling(co,"out",this,"out");


initialize();

    preferredSize = new Dimension(508, 32 + 80 * size);
    co.setPreferredLocation(new Point(-7, 20));
}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(987, 605);
        ((ViewableComponent)withName("proc17")).setPreferredLocation(new Point(187, 1302));
        ((ViewableComponent)withName("proc16")).setPreferredLocation(new Point(187, 1222));
        ((ViewableComponent)withName("proc1")).setPreferredLocation(new Point(187, 22));
        ((ViewableComponent)withName("proc7")).setPreferredLocation(new Point(187, 502));
        ((ViewableComponent)withName("proc13")).setPreferredLocation(new Point(187, 982));
        ((ViewableComponent)withName("proc6")).setPreferredLocation(new Point(187, 422));
        ((ViewableComponent)withName("proc12")).setPreferredLocation(new Point(187, 902));
        ((ViewableComponent)withName("proc15")).setPreferredLocation(new Point(187, 1142));
        ((ViewableComponent)withName("proc19")).setPreferredLocation(new Point(187, 1462));
        ((ViewableComponent)withName("MultiSco")).setPreferredLocation(new Point(-7, 20));
        ((ViewableComponent)withName("proc3")).setPreferredLocation(new Point(187, 182));
        ((ViewableComponent)withName("proc5")).setPreferredLocation(new Point(187, 342));
        ((ViewableComponent)withName("proc18")).setPreferredLocation(new Point(187, 1382));
        ((ViewableComponent)withName("proc10")).setPreferredLocation(new Point(187, 742));
        ((ViewableComponent)withName("proc11")).setPreferredLocation(new Point(187, 822));
        ((ViewableComponent)withName("proc20")).setPreferredLocation(new Point(187, 1542));
        ((ViewableComponent)withName("proc2")).setPreferredLocation(new Point(8, 125));
        ((ViewableComponent)withName("proc4")).setPreferredLocation(new Point(239, 368));
        ((ViewableComponent)withName("proc8")).setPreferredLocation(new Point(187, 582));
        ((ViewableComponent)withName("proc9")).setPreferredLocation(new Point(187, 662));
        ((ViewableComponent)withName("proc14")).setPreferredLocation(new Point(187, 1062));
    }
}
